name: Build and Deploy Spring Boot App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package

    - name: Deploy Jar (Example)
      run: |
        echo "Deploying app.jar to server..."
        # Here you could add scp or rsync commands to send the jar to a server
        echo "Simulated deploy: target/*.jar"
